import type { Product } from "./types";

const asset = (filename: string) => new URL(`../../../assets/${filename}`, import.meta.url).href;

export const PRODUCTS: Product[] = [
  {
    id: "p1",
    name: "Multi-Purpose Cleaner",
    shortDesc: "Cuts through grease and grime on everyday surfaces",
    price: 199,
    originalPrice: 249,
    rating: 4.7,
    reviewCount: 342,
    category: "Kitchen",
    brand: "Gleamtech",
    scent: "Citrus",
    isEco: false,
    inStock: true,
    image: asset("multi-purpose-cleaner.png"),
    badge: "Best Seller",
    sizes: ["500ml", "1L", "2L"],
    tags: ["kitchen", "multi-purpose", "spray"],
  },
  {
    id: "p2",
    name: "Dishwashing Liquid",
    shortDesc: "Tough on grease, gentle on hands",
    price: 149,
    originalPrice: undefined,
    rating: 4.5,
    reviewCount: 218,
    category: "Kitchen",
    brand: "Gleamtech",
    scent: "Lemon",
    isEco: true,
    inStock: true,
    image: asset("dishwashing-liquid.png"),
    badge: "Eco",
    sizes: ["450ml", "900ml"],
    tags: ["kitchen", "dish soap", "eco"],
  },
  {
    id: "p3",
    name: "Dishwashing Liquid V3",
    shortDesc: "Advanced grease-cutting formula for busy kitchens",
    price: 179,
    originalPrice: 219,
    rating: 4.6,
    reviewCount: 187,
    category: "Kitchen",
    brand: "Gleamtech",
    scent: "Lemon",
    isEco: true,
    inStock: true,
    image: asset("dishwashing-liquid-v3.png"),
    badge: "New",
    sizes: ["500ml", "1L"],
    tags: ["kitchen", "dish soap", "advanced"],
  },
  {
    id: "p4",
    name: "Bathroom Multi-Purpose Cleaner",
    shortDesc: "Brightens bathroom surfaces and removes residue",
    price: 199,
    originalPrice: undefined,
    rating: 4.6,
    reviewCount: 183,
    category: "Bathroom",
    brand: "Gleamtech",
    scent: "Fresh",
    isEco: false,
    inStock: true,
    image: asset("multi-purpose-cleaner.png"),
    badge: undefined,
    sizes: ["500ml", "750ml"],
    tags: ["bathroom", "multi-purpose", "spray"],
  },
  {
    id: "p5",
    name: "Floor Multi-Purpose Cleaner",
    shortDesc: "Streak-free clean for tiles and hard floors",
    price: 219,
    originalPrice: undefined,
    rating: 4.4,
    reviewCount: 129,
    category: "Floors",
    brand: "Gleamtech",
    scent: "Fresh",
    isEco: true,
    inStock: true,
    image: asset("multi-purpose-cleaner.png"),
    badge: "Eco",
    sizes: ["750ml", "2L"],
    tags: ["floor", "multi-purpose", "eco"],
  },
  {
    id: "p6",
    name: "Fabric Conditioner",
    shortDesc: "Softens fabric with a clean lasting scent",
    price: 189,
    originalPrice: undefined,
    rating: 4.8,
    reviewCount: 247,
    category: "Laundry",
    brand: "Gleamtech",
    scent: "Fresh Cotton",
    isEco: false,
    inStock: true,
    image: asset("fabric-conditioner.png"),
    badge: "Customer Pick",
    sizes: ["800ml", "1.5L"],
    tags: ["laundry", "fabric conditioner", "softener"],
  },
  {
    id: "p7",
    name: "Laundry Detergent Powder",
    shortDesc: "Deep-cleaning powder for everyday laundry",
    price: 249,
    originalPrice: 299,
    rating: 4.8,
    reviewCount: 507,
    category: "Laundry",
    brand: "Gleamtech",
    scent: "Fresh",
    isEco: false,
    inStock: true,
    image: asset("laundry-detergent-powder.png"),
    badge: "Best Value",
    sizes: ["1kg", "2kg", "4kg"],
    tags: ["laundry", "detergent", "powder"],
  },
  {
    id: "p8",
    name: "Laundry Detergent Liquid",
    shortDesc: "Liquid detergent for bright colors and fresh clothes",
    price: 279,
    originalPrice: undefined,
    rating: 4.7,
    reviewCount: 271,
    category: "Laundry",
    brand: "Gleamtech",
    scent: "Fresh",
    isEco: true,
    inStock: true,
    image: asset("laundry-liquid-detergent.png"),
    badge: "Eco",
    sizes: ["1L", "2L"],
    tags: ["laundry", "detergent", "liquid"],
  },
  {
    id: "p9",
    name: "Car Shampoo",
    shortDesc: "Foaming wash for a clean, glossy vehicle finish",
    price: 229,
    originalPrice: undefined,
    rating: 4.5,
    reviewCount: 98,
    category: "Others",
    brand: "Gleamtech",
    scent: "Fresh",
    isEco: false,
    inStock: true,
    image: asset("car-shampoo.png"),
    badge: "Auto Care",
    sizes: ["500ml", "1L"],
    tags: ["others", "car", "shampoo"],
  },
];

export const CATEGORIES = [
  { id: "kitchen", name: "Kitchen", icon: "Kitchen", count: 3, image: asset("dishwashing-liquid-v3.png"), color: "#EAF7E7" },
  { id: "bathroom", name: "Bathroom", icon: "Bath", count: 1, image: asset("multi-purpose-cleaner.png"), color: "#E8F7FA" },
  { id: "laundry", name: "Laundry", icon: "Laundry", count: 3, image: asset("laundry-detergent-powder.png"), color: "#EAF4FD" },
  { id: "floors", name: "Floors", icon: "Floors", count: 1, image: asset("multi-purpose-cleaner.png"), color: "#FFF6D8" },
  { id: "others", name: "Others", icon: "More", count: 1, image: asset("car-shampoo.png"), color: "#EAF7E7" },
];

export const REVIEWS = [
  { id: "r1", name: "Sarah M.", avatar: "SM", rating: 5, date: "Dec 2, 2024", text: "The multi-purpose cleaner is fantastic. I use it on everything from counters to stovetops.", product: "Multi-Purpose Cleaner", verified: true },
  { id: "r2", name: "James T.", avatar: "JT", rating: 5, date: "Nov 28, 2024", text: "Fast delivery and the laundry products smell clean without being too strong.", product: "Laundry Detergent Liquid", verified: true },
  { id: "r3", name: "Priya K.", avatar: "PK", rating: 4, date: "Nov 20, 2024", text: "Dishwashing liquid lathers really well and cuts grease quickly.", product: "Dishwashing Liquid", verified: true },
  { id: "r4", name: "Mike O.", avatar: "MO", rating: 5, date: "Nov 15, 2024", text: "The car shampoo foams nicely and leaves a good finish.", product: "Car Shampoo", verified: false },
];
