import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

function slugify(value: string) {
  return value
    .toLowerCase()
    .trim()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-+|-+$/g, '');
}

const products = [
  {
    id: 'p1',
    sku: 'GLEAM-MULTI-PURPOSE',
    slug: 'multi-purpose-cleaner',
    name: 'Multi-Purpose Cleaner',
    shortDescription: 'Cuts through grease and grime on everyday surfaces',
    description: 'A versatile cleaner for counters, appliances, tiles, bathrooms, and sealed surfaces.',
    priceMinor: 19900,
    originalPriceMinor: 24900,
    weightGrams: 500,
    isPublished: true,
    rating: 4.7,
    reviewCount: 342,
    category: 'Kitchen',
    brand: 'Gleamtech',
    scent: 'Citrus',
    isEco: false,
    image: '/assets/multi-purpose-cleaner.png',
    badge: 'Best Seller',
    sizes: ['500ml', '1L', '2L'],
    tags: ['kitchen', 'multi-purpose', 'spray'],
    stockQuantity: 50,
  },
  {
    id: 'p2',
    sku: 'GLEAM-DISH-LIQUID',
    slug: 'dishwashing-liquid',
    name: 'Dishwashing Liquid',
    shortDescription: 'Tough on grease, gentle on hands',
    description: 'A lemon-scented dish soap with strong grease removal and a gentle finish.',
    priceMinor: 14900,
    originalPriceMinor: null,
    weightGrams: 450,
    isPublished: true,
    rating: 4.5,
    reviewCount: 218,
    category: 'Kitchen',
    brand: 'Gleamtech',
    scent: 'Lemon',
    isEco: true,
    image: '/assets/dishwashing-liquid.png',
    badge: 'Eco',
    sizes: ['450ml', '900ml'],
    tags: ['kitchen', 'dish soap', 'eco'],
    stockQuantity: 45,
  },
  {
    id: 'p3',
    sku: 'GLEAM-DISH-LIQUID-V3',
    slug: 'dishwashing-liquid-v3',
    name: 'Dishwashing Liquid V3',
    shortDescription: 'Advanced grease-cutting formula for busy kitchens',
    description: 'An upgraded dishwashing liquid with improved grease-cutting performance.',
    priceMinor: 17900,
    originalPriceMinor: 21900,
    weightGrams: 500,
    isPublished: true,
    rating: 4.6,
    reviewCount: 187,
    category: 'Kitchen',
    brand: 'Gleamtech',
    scent: 'Lemon',
    isEco: true,
    image: '/assets/dishwashing-liquid-v3.png',
    badge: 'New',
    sizes: ['500ml', '1L'],
    tags: ['kitchen', 'dish soap', 'advanced'],
    stockQuantity: 45,
  },
  {
    id: 'p4',
    sku: 'GLEAM-BATH-MULTI',
    slug: 'bathroom-multi-purpose-cleaner',
    name: 'Bathroom Multi-Purpose Cleaner',
    shortDescription: 'Brightens bathroom surfaces and removes residue',
    description: 'A bathroom cleaner for sinks, counters, tiles, and other washable surfaces.',
    priceMinor: 19900,
    originalPriceMinor: null,
    weightGrams: 500,
    isPublished: true,
    rating: 4.6,
    reviewCount: 183,
    category: 'Bathroom',
    brand: 'Gleamtech',
    scent: 'Fresh',
    isEco: false,
    image: '/assets/multi-purpose-cleaner.png',
    badge: null,
    sizes: ['500ml', '750ml'],
    tags: ['bathroom', 'multi-purpose', 'spray'],
    stockQuantity: 35,
  },
  {
    id: 'p5',
    sku: 'GLEAM-FLOOR-MULTI',
    slug: 'floor-multi-purpose-cleaner',
    name: 'Floor Multi-Purpose Cleaner',
    shortDescription: 'Streak-free clean for tiles and hard floors',
    description: 'A multi-purpose cleaner suitable for tile and hard-floor cleaning.',
    priceMinor: 21900,
    originalPriceMinor: null,
    weightGrams: 750,
    isPublished: true,
    rating: 4.4,
    reviewCount: 129,
    category: 'Floors',
    brand: 'Gleamtech',
    scent: 'Fresh',
    isEco: true,
    image: '/assets/multi-purpose-cleaner.png',
    badge: 'Eco',
    sizes: ['750ml', '2L'],
    tags: ['floor', 'multi-purpose', 'eco'],
    stockQuantity: 30,
  },
  {
    id: 'p6',
    sku: 'GLEAM-FABRIC-CONDITIONER',
    slug: 'fabric-conditioner',
    name: 'Fabric Conditioner',
    shortDescription: 'Softens fabric with a clean lasting scent',
    description: 'A fabric conditioner for softer clothes and a fresh laundry finish.',
    priceMinor: 18900,
    originalPriceMinor: null,
    weightGrams: 800,
    isPublished: true,
    rating: 4.8,
    reviewCount: 247,
    category: 'Laundry',
    brand: 'Gleamtech',
    scent: 'Fresh Cotton',
    isEco: false,
    image: '/assets/fabric-conditioner.png',
    badge: 'Customer Pick',
    sizes: ['800ml', '1.5L'],
    tags: ['laundry', 'fabric conditioner', 'softener'],
    stockQuantity: 40,
  },
  {
    id: 'p7',
    sku: 'GLEAM-LAUNDRY-POWDER',
    slug: 'laundry-detergent-powder',
    name: 'Laundry Detergent Powder',
    shortDescription: 'Deep-cleaning powder for everyday laundry',
    description: 'Powder detergent for bright laundry and everyday stain removal.',
    priceMinor: 24900,
    originalPriceMinor: 29900,
    weightGrams: 1000,
    isPublished: true,
    rating: 4.8,
    reviewCount: 507,
    category: 'Laundry',
    brand: 'Gleamtech',
    scent: 'Fresh',
    isEco: false,
    image: '/assets/laundry-detergent-powder.png',
    badge: 'Best Value',
    sizes: ['1kg', '2kg', '4kg'],
    tags: ['laundry', 'detergent', 'powder'],
    stockQuantity: 40,
  },
  {
    id: 'p8',
    sku: 'GLEAM-LAUNDRY-LIQUID',
    slug: 'laundry-detergent-liquid',
    name: 'Laundry Detergent Liquid',
    shortDescription: 'Liquid detergent for bright colors and fresh clothes',
    description: 'Liquid detergent for clean clothes and a fresh laundry scent.',
    priceMinor: 27900,
    originalPriceMinor: null,
    weightGrams: 1000,
    isPublished: true,
    rating: 4.7,
    reviewCount: 271,
    category: 'Laundry',
    brand: 'Gleamtech',
    scent: 'Fresh',
    isEco: true,
    image: '/assets/laundry-liquid-detergent.png',
    badge: 'Eco',
    sizes: ['1L', '2L'],
    tags: ['laundry', 'detergent', 'liquid'],
    stockQuantity: 35,
  },
  {
    id: 'p9',
    sku: 'GLEAM-CAR-SHAMPOO',
    slug: 'car-shampoo',
    name: 'Car Shampoo',
    shortDescription: 'Foaming wash for a clean, glossy vehicle finish',
    description: 'A car shampoo that foams well and leaves a clean finish.',
    priceMinor: 22900,
    originalPriceMinor: null,
    weightGrams: 500,
    isPublished: true,
    rating: 4.5,
    reviewCount: 98,
    category: 'Others',
    brand: 'Gleamtech',
    scent: 'Fresh',
    isEco: false,
    image: '/assets/car-shampoo.png',
    badge: 'Auto Care',
    sizes: ['500ml', '1L'],
    tags: ['others', 'car', 'shampoo'],
    stockQuantity: 30,
  },
];

async function main() {
  for (const product of products) {
    const { stockQuantity, ...data } = product;
    await prisma.product.upsert({
      where: { id: product.id },
      update: { ...data, slug: data.slug || slugify(data.name) },
      create: { ...data, slug: data.slug || slugify(data.name) },
    });
    await prisma.inventory.upsert({
      where: { productId: product.id },
      update: { stockQuantity },
      create: { productId: product.id, stockQuantity },
    });
  }
}

main()
  .then(async () => {
    await prisma.$disconnect();
  })
  .catch(async error => {
    console.error(error);
    await prisma.$disconnect();
    process.exit(1);
  });
