import { PrismaClient } from '@prisma/client';
const prisma = new PrismaClient();
const products = [
    {
        id: 'p1',
        sku: 'SPARKLE-MULTI-CITRUS',
        name: 'Multi-Surface Cleaner',
        shortDescription: 'Cuts through grease and grime on any surface',
        description: 'A versatile citrus cleaner for counters, appliances, tiles, and sealed surfaces.',
        priceMinor: 899,
        originalPriceMinor: 1199,
        rating: 4.7,
        reviewCount: 342,
        category: 'Kitchen',
        brand: 'SparkleClean',
        scent: 'Citrus',
        isEco: false,
        image: 'https://images.unsplash.com/photo-1585771724684-38269d6639fd?w=400&h=400&fit=crop&auto=format',
        badge: 'Best Seller',
        sizes: ['500ml', '1L', '2L'],
        tags: ['kitchen', 'multi-surface', 'spray'],
        stockQuantity: 50,
    },
    {
        id: 'p2',
        sku: 'FRESHWAVE-DISH-LEMON',
        name: 'Lemon Dishwashing Liquid',
        shortDescription: 'Tough on grease, gentle on hands',
        description: 'A lemon-scented dish soap with strong grease removal and a gentle finish.',
        priceMinor: 449,
        originalPriceMinor: null,
        rating: 4.5,
        reviewCount: 218,
        category: 'Kitchen',
        brand: 'FreshWave',
        scent: 'Lemon',
        isEco: true,
        image: 'https://images.unsplash.com/photo-1607619056574-7b8d3ee536b2?w=400&h=400&fit=crop&auto=format',
        badge: 'Eco',
        sizes: ['450ml', '900ml'],
        tags: ['kitchen', 'dish soap', 'eco'],
        stockQuantity: 45,
    },
    {
        id: 'p3',
        sku: 'TIDYWHITE-LAUNDRY-LAVENDER',
        name: 'Laundry Detergent',
        shortDescription: 'Deep clean with a lasting fresh scent',
        description: 'Concentrated detergent for bright colors and fresh lavender laundry.',
        priceMinor: 1299,
        originalPriceMinor: 1599,
        rating: 4.8,
        reviewCount: 507,
        category: 'Laundry',
        brand: 'TidyWhite',
        scent: 'Lavender',
        isEco: false,
        image: 'https://images.unsplash.com/photo-1558769132-cb1aea458c5e?w=400&h=400&fit=crop&auto=format',
        badge: '25% Off',
        sizes: ['1kg', '2kg', '4kg'],
        tags: ['laundry', 'detergent', 'lavender'],
        stockQuantity: 40,
    },
    {
        id: 'p4',
        sku: 'GERMSHIELD-BATH-PINE',
        name: 'Bathroom Disinfectant Spray',
        shortDescription: 'Kills 99.9% of bacteria and viruses',
        description: 'Pine-fresh disinfectant spray for bathrooms and high-touch hard surfaces.',
        priceMinor: 799,
        originalPriceMinor: null,
        rating: 4.6,
        reviewCount: 183,
        category: 'Bathroom',
        brand: 'GermShield',
        scent: 'Pine Fresh',
        isEco: false,
        image: 'https://images.unsplash.com/photo-1584820927498-cfe5211fd8bf?w=400&h=400&fit=crop&auto=format',
        badge: null,
        sizes: ['500ml', '750ml'],
        tags: ['bathroom', 'disinfectant', 'spray'],
        stockQuantity: 35,
    },
    {
        id: 'p5',
        sku: 'FLOORGLOSS-CONCENTRATE-MINT',
        name: 'Floor Cleaner Concentrate',
        shortDescription: 'Streak-free shine on all hard floors',
        description: 'Mint concentrate for hard floors with a streak-free finish.',
        priceMinor: 949,
        originalPriceMinor: null,
        rating: 4.4,
        reviewCount: 129,
        category: 'Floors',
        brand: 'FloorGloss',
        scent: 'Mint',
        isEco: true,
        image: 'https://images.unsplash.com/photo-1584622781564-1d987f7333c1?w=400&h=400&fit=crop&auto=format',
        badge: 'Eco',
        sizes: ['750ml', '2L'],
        tags: ['floor', 'concentrate', 'eco'],
        stockQuantity: 30,
    },
    {
        id: 'p6',
        sku: 'GREENHOME-ECO-BUNDLE',
        name: 'Eco-Friendly Cleaning Bundle',
        shortDescription: 'Complete eco kit for the whole home',
        description: 'A complete plant-based cleaning kit for kitchen, bathroom, laundry, and floors.',
        priceMinor: 3499,
        originalPriceMinor: 4999,
        rating: 4.9,
        reviewCount: 94,
        category: 'Eco-Friendly',
        brand: 'GreenHome',
        scent: null,
        isEco: true,
        image: 'https://images.unsplash.com/photo-1542838132-92c53300491e?w=400&h=400&fit=crop&auto=format',
        badge: 'Bundle Deal',
        sizes: ['Kit'],
        tags: ['eco', 'bundle', 'natural'],
        stockQuantity: 20,
    },
    {
        id: 'p7',
        sku: 'GERMSHIELD-TOILET-OCEAN',
        name: 'Toilet Bowl Cleaner',
        shortDescription: 'Thick gel clings and deep cleans under the rim',
        description: 'Ocean breeze toilet gel designed to cling under the rim for deeper cleaning.',
        priceMinor: 549,
        originalPriceMinor: null,
        rating: 4.3,
        reviewCount: 156,
        category: 'Bathroom',
        brand: 'GermShield',
        scent: 'Ocean Breeze',
        isEco: false,
        image: 'https://images.unsplash.com/photo-1563453392212-326f5e854473?w=400&h=400&fit=crop&auto=format',
        badge: null,
        sizes: ['500ml', '1L'],
        tags: ['bathroom', 'toilet', 'gel'],
        stockQuantity: 30,
    },
    {
        id: 'p8',
        sku: 'GREENHOME-NATURAL-EUCALYPTUS',
        name: 'Natural All-Purpose Spray',
        shortDescription: 'Plant-based formula, safe for kids and pets',
        description: 'Eucalyptus all-purpose spray made with plant-derived cleaning agents.',
        priceMinor: 1099,
        originalPriceMinor: null,
        rating: 4.7,
        reviewCount: 271,
        category: 'Eco-Friendly',
        brand: 'GreenHome',
        scent: 'Eucalyptus',
        isEco: true,
        image: 'https://images.unsplash.com/photo-1628177142898-93e36e4e3a50?w=400&h=400&fit=crop&auto=format',
        badge: 'Out of Stock',
        sizes: ['500ml'],
        tags: ['eco', 'natural', 'all-purpose'],
        stockQuantity: 0,
    },
];
async function main() {
    for (const product of products) {
        const { stockQuantity, ...data } = product;
        await prisma.product.upsert({
            where: { id: product.id },
            update: data,
            create: data,
        });
        await prisma.inventory.upsert({
            where: { productId: product.id },
            update: { stockQuantity },
            create: { productId: product.id, stockQuantity },
        });
    }
}
main()
    .then(async () => {
    await prisma.$disconnect();
})
    .catch(async (error) => {
    console.error(error);
    await prisma.$disconnect();
    process.exit(1);
});
