import React, { useCallback, useEffect, useMemo, useState } from "react";
import { Building2, ClipboardList, Plus, Search, X } from "lucide-react";
import { toast } from "sonner";
import { api, ApiClientError, type AdminProduct, type WholesaleAccount, type WholesaleAccountInput, type WholesaleDashboard, type WholesaleOrder } from "../../api";
import { formatCurrency } from "../currency";

const blankAccount: WholesaleAccountInput = { companyName: "", contactName: "", email: "", phone: "", taxId: "", billingAddress: "", shippingAddress: "", priceTier: "STANDARD", paymentTermDays: 0, creditLimitMinor: 0, minimumOrderMinor: 0, status: "ACTIVE", notes: "" };
const orderStatuses = ["DRAFT", "CONFIRMED", "PROCESSING", "READY", "SHIPPED", "COMPLETED", "CANCELLED"];
const paymentStatuses = ["UNPAID", "PARTIALLY_PAID", "PAID", "OVERDUE", "VOID"];
const message = (error: unknown) => error instanceof ApiClientError ? error.body.message : error instanceof Error ? error.message : "Request failed.";

export function AdminWholesalePage() {
  const [tab, setTab] = useState<"orders" | "accounts">("orders");
  const [dashboard, setDashboard] = useState<WholesaleDashboard | null>(null);
  const [accounts, setAccounts] = useState<WholesaleAccount[]>([]);
  const [orders, setOrders] = useState<WholesaleOrder[]>([]);
  const [products, setProducts] = useState<AdminProduct[]>([]);
  const [search, setSearch] = useState("");
  const [loading, setLoading] = useState(true);
  const [accountForm, setAccountForm] = useState<WholesaleAccountInput | null>(null);
  const [editingAccountId, setEditingAccountId] = useState<string | null>(null);
  const [orderOpen, setOrderOpen] = useState(false);
  const [saving, setSaving] = useState(false);
  const [orderForm, setOrderForm] = useState({ accountId: "", purchaseOrderNumber: "", discount: "0", notes: "", items: [{ productId: "", quantity: 1, unitPrice: "" }] });
  const query = useMemo(() => search.trim() ? `?page=1&pageSize=100&search=${encodeURIComponent(search.trim())}` : "?page=1&pageSize=100", [search]);

  const load = useCallback(async () => {
    setLoading(true);
    try {
      const [summary, accountResult, orderResult, productResult] = await Promise.all([api.adminWholesaleDashboard(), api.adminWholesaleAccounts(query), api.adminWholesaleOrders(query), api.adminProducts("?page=1&pageSize=100")]);
      setDashboard(summary.dashboard); setAccounts(accountResult.accounts); setOrders(orderResult.orders); setProducts(productResult.products);
    } catch (error) { toast.error(message(error)); } finally { setLoading(false); }
  }, [query]);
  useEffect(() => { void load(); }, [load]);

  const saveAccount = async () => {
    if (!accountForm) return;
    setSaving(true);
    try {
      if (editingAccountId) await api.adminUpdateWholesaleAccount(editingAccountId, accountForm); else await api.adminCreateWholesaleAccount(accountForm);
      toast.success(editingAccountId ? "Wholesale account updated" : "Wholesale account created"); setAccountForm(null); setEditingAccountId(null); await load();
    } catch (error) { toast.error(message(error)); } finally { setSaving(false); }
  };
  const editAccount = (account: WholesaleAccount) => { setEditingAccountId(account.id); setAccountForm({ companyName: account.companyName, contactName: account.contactName, email: account.email, phone: account.phone, taxId: account.taxId ?? "", billingAddress: account.billingAddress, shippingAddress: account.shippingAddress, priceTier: account.priceTier, paymentTermDays: account.paymentTermDays, creditLimitMinor: account.creditLimitMinor, minimumOrderMinor: account.minimumOrderMinor, status: account.status, notes: account.notes ?? "" }); };
  const createOrder = async () => {
    setSaving(true);
    try {
      await api.adminCreateWholesaleOrder({ accountId: orderForm.accountId, purchaseOrderNumber: orderForm.purchaseOrderNumber || undefined, discountMinor: Math.round(Number(orderForm.discount || 0) * 100), notes: orderForm.notes || undefined, items: orderForm.items.map(item => ({ productId: item.productId, quantity: Number(item.quantity), unitPriceMinor: Math.round(Number(item.unitPrice) * 100) })) });
      toast.success("Wholesale order created"); setOrderOpen(false); setOrderForm({ accountId: "", purchaseOrderNumber: "", discount: "0", notes: "", items: [{ productId: "", quantity: 1, unitPrice: "" }] }); await load();
    } catch (error) { toast.error(message(error)); } finally { setSaving(false); }
  };
  const updateOrder = async (order: WholesaleOrder, status: string, paymentStatus: string) => { try { await api.adminUpdateWholesaleOrder(order.id, status, paymentStatus); toast.success("Order updated"); await load(); } catch (error) { toast.error(message(error)); } };

  return <main className="mx-auto max-w-7xl px-4 py-8 sm:px-6">
    <div className="mb-6 flex flex-wrap items-end justify-between gap-4"><div><p className="text-sm font-semibold uppercase tracking-widest text-[var(--green)]">Administrator only</p><h1 className="mt-1 text-3xl font-bold">Wholesale OMS</h1><p className="mt-1 text-sm text-muted-foreground">Manage B2B accounts, purchase orders, payment terms, and fulfillment.</p></div><div className="flex gap-2"><button onClick={() => { setEditingAccountId(null); setAccountForm(blankAccount); }} className="h-10 rounded-xl border border-border px-4 text-sm font-semibold">New account</button><button onClick={() => setOrderOpen(true)} className="inline-flex h-10 items-center gap-2 rounded-xl bg-primary px-4 text-sm font-semibold text-primary-foreground"><Plus size={16}/> New order</button></div></div>
    <section className="mb-6 grid gap-3 sm:grid-cols-2 lg:grid-cols-5">{[["Active accounts", dashboard?.activeAccounts ?? 0],["Open orders",dashboard?.openOrders ?? 0],["Awaiting payment",dashboard?.unpaidOrders ?? 0],["Overdue",dashboard?.overdueOrders ?? 0],["Order value",formatCurrency(dashboard?.totalOrderValue ?? 0)]].map(([label,value]) => <div key={label} className="rounded-2xl border border-border bg-card p-4"><p className="text-xs font-semibold uppercase tracking-wide text-muted-foreground">{label}</p><p className="mt-2 text-2xl font-bold">{value}</p></div>)}</section>
    <div className="mb-4 flex flex-wrap items-center justify-between gap-3"><div className="flex rounded-xl border border-border bg-card p-1"><button onClick={() => setTab("orders")} className={`rounded-lg px-4 py-2 text-sm font-semibold ${tab === "orders" ? "bg-secondary" : ""}`}><ClipboardList size={15} className="mr-2 inline"/>Orders</button><button onClick={() => setTab("accounts")} className={`rounded-lg px-4 py-2 text-sm font-semibold ${tab === "accounts" ? "bg-secondary" : ""}`}><Building2 size={15} className="mr-2 inline"/>Accounts</button></div><label className="relative"><Search size={15} className="absolute left-3 top-1/2 -translate-y-1/2 text-muted-foreground"/><input value={search} onChange={e => setSearch(e.target.value)} placeholder="Search wholesale..." className="h-10 rounded-xl border border-border bg-card pl-9 pr-3 text-sm"/></label></div>
    {loading ? <div className="rounded-2xl border border-border p-10 text-center text-sm text-muted-foreground">Loading wholesale records...</div> : tab === "accounts" ? <section className="overflow-hidden rounded-2xl border border-border bg-card"><div className="hidden grid-cols-[1.3fr_1fr_100px_120px_110px] gap-3 border-b px-4 py-3 text-xs font-semibold uppercase text-muted-foreground lg:grid"><span>Company</span><span>Contact</span><span>Terms</span><span>Outstanding</span><span></span></div>{accounts.map(account => <div key={account.id} className="grid gap-3 border-b border-border px-4 py-4 last:border-0 lg:grid-cols-[1.3fr_1fr_100px_120px_110px] lg:items-center"><div><p className="font-semibold">{account.companyName}</p><p className="text-xs text-muted-foreground">{account.priceTier} · {account.status} · {account.orderCount} orders</p></div><div><p className="text-sm">{account.contactName}</p><p className="text-xs text-muted-foreground">{account.email}</p></div><p className="text-sm">Net {account.paymentTermDays}</p><p className="font-semibold">{formatCurrency(account.outstanding)}</p><button onClick={() => editAccount(account)} className="h-9 rounded-xl border border-border text-sm font-semibold">Edit</button></div>)}</section> : <section className="overflow-hidden rounded-2xl border border-border bg-card"><div className="hidden grid-cols-[1fr_1.2fr_100px_100px_145px_145px] gap-3 border-b px-4 py-3 text-xs font-semibold uppercase text-muted-foreground lg:grid"><span>Order</span><span>Account</span><span>PO</span><span>Total</span><span>Fulfillment</span><span>Payment</span></div>{orders.map(order => <div key={order.id} className="grid gap-3 border-b border-border px-4 py-4 last:border-0 lg:grid-cols-[1fr_1.2fr_100px_100px_145px_145px] lg:items-center"><div><p className="font-semibold">{order.orderNumber}</p><p className="text-xs text-muted-foreground">{new Date(order.createdAt).toLocaleDateString()} · {order.itemCount} items</p></div><p className="text-sm font-medium">{order.account.companyName}</p><p className="text-sm">{order.purchaseOrderNumber || "—"}</p><p className="font-semibold">{formatCurrency(order.total)}</p><select value={order.status} onChange={e => updateOrder(order,e.target.value,order.paymentStatus)} className="h-9 rounded-lg border bg-card px-2 text-xs">{orderStatuses.map(s => <option key={s}>{s}</option>)}</select><select value={order.paymentStatus} onChange={e => updateOrder(order,order.status,e.target.value)} className="h-9 rounded-lg border bg-card px-2 text-xs">{paymentStatuses.map(s => <option key={s}>{s}</option>)}</select></div>)}</section>}
    {accountForm && <Modal title={editingAccountId ? "Edit wholesale account" : "New wholesale account"} onClose={() => setAccountForm(null)}><div className="grid gap-3 sm:grid-cols-2">{([['companyName','Company name'],['contactName','Contact name'],['email','Email'],['phone','Phone'],['taxId','Tax ID'],['priceTier','Price tier']] as const).map(([key,label]) => <Field key={key} label={label} value={String(accountForm[key] ?? '')} onChange={value => setAccountForm({...accountForm,[key]:value})}/>)}</div><div className="mt-3 grid gap-3"><Field label="Billing address" value={accountForm.billingAddress} onChange={value => setAccountForm({...accountForm,billingAddress:value})}/><Field label="Shipping address" value={accountForm.shippingAddress} onChange={value => setAccountForm({...accountForm,shippingAddress:value})}/><div className="grid gap-3 sm:grid-cols-3"><Field label="Payment terms (days)" type="number" value={String(accountForm.paymentTermDays)} onChange={value => setAccountForm({...accountForm,paymentTermDays:Number(value)})}/><Field label="Credit limit" type="number" value={String(accountForm.creditLimitMinor/100)} onChange={value => setAccountForm({...accountForm,creditLimitMinor:Math.round(Number(value)*100)})}/><Field label="Minimum order" type="number" value={String(accountForm.minimumOrderMinor/100)} onChange={value => setAccountForm({...accountForm,minimumOrderMinor:Math.round(Number(value)*100)})}/></div><label className="text-sm font-medium">Status<select value={accountForm.status} onChange={e => setAccountForm({...accountForm,status:e.target.value as WholesaleAccountInput['status']})} className="mt-1 h-10 w-full rounded-xl border bg-card px-3"><option>ACTIVE</option><option>ON_HOLD</option><option>CLOSED</option></select></label><Field label="Internal notes" value={accountForm.notes ?? ''} onChange={value => setAccountForm({...accountForm,notes:value})}/><button disabled={saving} onClick={saveAccount} className="h-11 rounded-xl bg-primary font-semibold text-primary-foreground disabled:opacity-50">Save account</button></div></Modal>}
    {orderOpen && <Modal title="Create wholesale order" onClose={() => setOrderOpen(false)}><div className="grid gap-3"><label className="text-sm font-medium">Business account<select value={orderForm.accountId} onChange={e => setOrderForm({...orderForm,accountId:e.target.value})} className="mt-1 h-10 w-full rounded-xl border bg-card px-3"><option value="">Select account</option>{accounts.filter(a => a.status === 'ACTIVE').map(a => <option key={a.id} value={a.id}>{a.companyName}</option>)}</select></label><Field label="Customer PO number" value={orderForm.purchaseOrderNumber} onChange={value => setOrderForm({...orderForm,purchaseOrderNumber:value})}/>{orderForm.items.map((item,index) => <div key={index} className="grid gap-2 rounded-xl border p-3 sm:grid-cols-[1fr_90px_120px_40px]"><select value={item.productId} onChange={e => { const next=[...orderForm.items]; const product=products.find(p=>p.id===e.target.value); next[index]={...item,productId:e.target.value,unitPrice:product?String(product.priceCents/100):item.unitPrice}; setOrderForm({...orderForm,items:next}); }} className="h-10 rounded-lg border bg-card px-2"><option value="">Select product</option>{products.map(p=><option key={p.id} value={p.id}>{p.sku} — {p.name}</option>)}</select><input type="number" min="1" value={item.quantity} onChange={e=>{const next=[...orderForm.items];next[index]={...item,quantity:Number(e.target.value)};setOrderForm({...orderForm,items:next});}} className="h-10 rounded-lg border bg-card px-2"/><input type="number" min="0" step="0.01" value={item.unitPrice} onChange={e=>{const next=[...orderForm.items];next[index]={...item,unitPrice:e.target.value};setOrderForm({...orderForm,items:next});}} placeholder="Unit price" className="h-10 rounded-lg border bg-card px-2"/><button disabled={orderForm.items.length===1} onClick={()=>setOrderForm({...orderForm,items:orderForm.items.filter((_,i)=>i!==index)})} className="text-muted-foreground"><X size={16}/></button></div>)}<button onClick={()=>setOrderForm({...orderForm,items:[...orderForm.items,{productId:"",quantity:1,unitPrice:""}]})} className="h-9 rounded-xl border text-sm font-semibold">Add line item</button><Field label="Discount" type="number" value={orderForm.discount} onChange={value=>setOrderForm({...orderForm,discount:value})}/><Field label="Internal notes" value={orderForm.notes} onChange={value=>setOrderForm({...orderForm,notes:value})}/><button disabled={saving} onClick={createOrder} className="h-11 rounded-xl bg-primary font-semibold text-primary-foreground disabled:opacity-50">Create order</button></div></Modal>}
  </main>;
}

function Field({label,value,onChange,type="text"}:{label:string;value:string;onChange:(value:string)=>void;type?:string}) { return <label className="text-sm font-medium">{label}<input required type={type} value={value} onChange={e=>onChange(e.target.value)} className="mt-1 h-10 w-full rounded-xl border border-border bg-card px-3"/></label>; }
function Modal({title,onClose,children}:{title:string;onClose:()=>void;children:React.ReactNode}) { return <div className="fixed inset-0 z-[90] flex items-center justify-center bg-black/45 p-4"><div className="max-h-[92vh] w-full max-w-3xl overflow-y-auto rounded-2xl border border-border bg-card p-5 shadow-2xl"><div className="mb-4 flex items-center justify-between"><h2 className="text-xl font-bold">{title}</h2><button onClick={onClose} className="rounded-lg p-2 hover:bg-secondary"><X size={18}/></button></div>{children}</div></div>; }
