import { HttpException, HttpStatus } from '@nestjs/common';

export type ApiErrorCode =
  | 'INVALID_CREDENTIALS'
  | 'EMAIL_ALREADY_EXISTS'
  | 'AUTHENTICATION_REQUIRED'
  | 'ADMIN_REQUIRED'
  | 'USER_NOT_FOUND'
  | 'PRODUCT_NOT_FOUND'
  | 'SKU_ALREADY_EXISTS'
  | 'INVALID_PRODUCT_PRICE'
  | 'INVALID_PRODUCT_WEIGHT'
  | 'INVALID_STOCK_QUANTITY'
  | 'PRODUCT_IMAGE_INVALID'
  | 'PRODUCT_IMAGE_TOO_LARGE'
  | 'PRODUCT_IMAGE_LIMIT_EXCEEDED'
  | 'PRODUCT_IMAGE_INVALID_ORDER'
  | 'PRODUCT_ARCHIVED'
  | 'PRODUCT_UNAVAILABLE'
  | 'INSUFFICIENT_STOCK'
  | 'REVIEW_NOT_ALLOWED'
  | 'EMPTY_CART'
  | 'CHECKOUT_RETRY_EXHAUSTED'
  | 'ORDER_NUMBER_FAILED'
  | 'ORDER_NOT_FOUND'
  | 'ORDER_CANCELLATION_NOT_ALLOWED'
  | 'ORDER_REQUEST_NOT_ALLOWED'
  | 'ORDER_REQUEST_NOT_FOUND'
  | 'INVALID_ORDER_STATUS'
  | 'INVALID_ORDER_STATUS_TRANSITION'
  | 'PAYMENT_STATUS_RESTRICTED'
  | 'PAYMENT_CONFIRMATION_EMAIL_FAILED'
  | 'PROMO_NOT_FOUND'
  | 'INVALID_PROMO_DATE'
  | 'INVALID_PROMO_DATE_RANGE'
  | 'INVALID_DATE_RANGE'
  | 'INVALID_ANALYTICS_FILTER'
  | 'ANALYTICS_DATA_UNAVAILABLE'
  | 'PAYMENT_FAILED'
  | 'VALIDATION_ERROR'
  | 'CSRF_TOKEN_INVALID'
  | 'ACCOUNT_NOT_FOUND'
  | 'PASSWORD_REQUIRED'
  | 'PASSWORD_RESET_INVALID'
  | 'WISHLIST_ITEM_NOT_FOUND'
  | 'TWO_FACTOR_REQUIRED'
  | 'TWO_FACTOR_NOT_ENABLED'
  | 'TWO_FACTOR_ALREADY_ENABLED'
  | 'TWO_FACTOR_SETUP_REQUIRED'
  | 'INVALID_TWO_FACTOR_CODE'
  | 'INVALID_TWO_FACTOR_CHALLENGE'
  | 'INVALID_TOTP_SECRET'
  | 'TOTP_SECRET_UNREADABLE'
  | 'TOTP_KEY_REQUIRED'
  | 'TOTP_QR_DATA_TOO_LONG'
  | 'INVALID_OAUTH_STATE'
  | 'CONFIGURATION_ERROR'
  | 'OAUTH_TOKEN_EXCHANGE_FAILED'
  | 'OAUTH_PROFILE_FAILED'
  | 'OAUTH_EMAIL_REQUIRED'
  | 'INVALID_GOOGLE_CREDENTIAL';

export class ApiError extends HttpException {
  constructor(
    statusCode: HttpStatus,
    public readonly code: ApiErrorCode,
    message: string,
    public readonly details?: Record<string, unknown>,
  ) {
    super({ statusCode, code, message, details }, statusCode);
  }
}
